"""add max photo fields to product_photo

Revision ID: df15104d0e4b
Revises: e5db72bd462f
Create Date: 2026-05-08 00:51:14.500443

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df15104d0e4b"
down_revision: str | None = "e5db72bd462f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_photos', sa.Column('max_photo_id', sa.Integer(), nullable=True))
    op.add_column('product_photos', sa.Column('max_photo_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_photos', 'max_photo_token')
    op.drop_column('product_photos', 'max_photo_id')
    # ### end Alembic commands ###
